### ISSUE TITLE
dashboard improvements

### ISSUE THREAD

**Issue by kgjamieson** [nextml/NEXT#37]
I've started a new branch - board-improvements in an effort to convert our plotting library over to mpld3: http://mpld3.github.io/

The dashboards are considerably lighter than before and support zooming. Additional features like tooltips are easily added as well.

I've also moved AppDashboard.py into next/dashboard and added a basic.html page that is defaulted to with all these common graphs if an app-specific dashbaord is not specified in next/apps/[{ app_id }}/dashbaord. 

So far I've converted all of the existing basic plots common to all algorithms (quick and dirty, they're not the prettiest thing in the world). What's left:
1) Add descriptions of each section describing what is being plotted, how its being calculated, and why its useful for the users to look at
2) Tabbing for the different algorithms http://getbootstrap.com/javascript/#tabs
3) Update logic in next/dashboard/dashboard.py so that it first looks for the dashboard html file in next/apps/[{ app_id }}/dashbaord but if it fails it will default to next/dashboard/templates/basic.html (I think a try catch should work here)
4) Make the activity histogram at the top look sexy _and_ informative. I never found these histograms so useful, so at the very least they could look pretty
5) Add links on basic.html for query view and to download participants so that the dashboard the ultimate one-top-shop for all statistics. We could also move the "system" links to the dashboard - maybe put a real-time CPU plot there

**Comment by scottsievert** [comment]
On (3), look at [seaborn], a statistical package from Stanford to make matplotlib plots attractive. With two lines of code, it'll *temporarily* make new matplotlib defaults to make the plots look *really* good. Check out their [example gallery]. Because it writes new defaults, it'll work with `mpld3.fig_to_dict`.

Making plots look sexy is easy: all that's required is

```python
import seaborn as sns
sns.set() # new attractive defaults!
```

[seaborn]:http://stanford.edu/~mwaskom/software/seaborn/
[example gallery]:http://stanford.edu/~mwaskom/software/seaborn/examples/index.html#example-gallery
